### ISSUE TITLE
How'd you install the plugin from within Intellij ?

### ISSUE THREAD

**Issue by paul-hammant** [cuppa-framework/cuppa-intellij-plugin#4]
![image](https://user-images.githubusercontent.com/82182/38203803-6e476fb0-366e-11e8-898b-48f39407e969.png)

**Comment by joebandenburg** [comment]
Hi Paul. I believe that the version number just needs to be bumped to let IntelliJ know that the plugin is compatible with the latest version. There's actually two PRs open for this.

**Comment by paul-hammant** [comment]
I took one or the PRs for 2017, cloned that and changed it again for 2018, and yes the plugin now installs.

**Comment by joebandenburg** [comment]
I've merged #5 to add support for 2018.1 and submitted a new version to Jetbrains. It should hopefully appear in the list once the new version is approved.
